Python Kafka Consumption Example
STFC-ICD-Research-and-Design/supermusr-data-pipeline-extra pull request #2
Opened 2023-11-16 15:51 UTC by Henry-Denny

Closes #1.

2023-11-17 09:29 UTC, DanNixon requested changes
Looks good, just a few comments.

This repo will have more than just this code in it eventually, so can this be put in a new directory. Also include a README.md explaining what this is.

Could some form of dependency management also be used (whatever the default is for Python now).

2023-11-17 09:29 UTC, DanNixon commented on consumer.py
> +def listen(trace_topic: str):
Where should the broker address be set?

2023-11-17 09:29 UTC, DanNixon commented on consumer.py
> +def display_payload_information(payload: DigitizerEventListMessage):
Where are the actual events? This just prints the metadata.

2023-11-17 09:29 UTC, DanNixon commented on schemas/aev1_frame_assembled_event_v1.fbs
> +include "frame_metadata_v1.fbs";
Do not include the schemas here, the single source of truth for those is https://github.com/STFC-ICD-Research-and-Design/supermusr-data-pipeline

2023-11-21 15:49 UTC, DanNixon requested changes
Could the `demos` directory be renamed something more descriptive (reflecting what the example actually does).

Not sure the `__init__.py` at the repository root is needed.

There is no actual event information printed, could a summary of the events in the message be added?

2023-11-21 17:20 UTC, Henry-Denny commented
I'm not sure exactly what you mean by the event information. Would that be the `Voltage` and `Channel` fields?

2023-11-21 17:44 UTC, DanNixon commented
> I'm not sure exactly what you mean by the event information. Would that be the `Voltage` and `Channel` fields?

Yes, but just print the number of events and first 5 or so elements since these contain a lot of data.

2023-11-22 10:16 UTC, DanNixon approved these changes

2023-11-22 10:16 UTC, merged